<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Supplier;
use Illuminate\Support\Facades\DB;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'supplier_number' => 'SUP-000001',
                'name' => 'مؤسسة الشروق التجارية',
                'email' => 'info@alshoroq.om',
                'phone' => '+968 24123456',
                'address' => 'مسقط، روي، شارع السلطان قابوس',
                'nationality' => 'عماني',
                'supplier_type' => 'COMPANY',
                'commercial_record' => 'CR-2020-12345',
                'tax_number' => 'TAX-OM-123456',
                'status' => 'ACTIVE',
                'registration_date' => '2020-01-15',
                'contact_person' => 'أحمد بن سالم المعمري',
                'contact_person_phone' => '+968 99123456',
                'contact_person_email' => 'ahmed@alshoroq.om',
                'bank_name' => 'بنك مسقط',
                'bank_account' => '0123456789',
                'iban' => 'OM12BMAG0123456789012345',
                'swift_code' => 'BMAGOMR1',
                'notes' => 'مورد موثوق، يوفر معدات سقالات عالية الجودة',
                'rating' => 5,
            ],
            [
                'supplier_number' => 'SUP-000002',
                'name' => 'شركة النهضة للمعدات',
                'email' => 'sales@alnahda.om',
                'phone' => '+968 24234567',
                'address' => 'صلالة، المدينة الصناعية',
                'nationality' => 'عماني',
                'supplier_type' => 'COMPANY',
                'commercial_record' => 'CR-2019-23456',
                'tax_number' => 'TAX-OM-234567',
                'status' => 'ACTIVE',
                'registration_date' => '2019-06-20',
                'contact_person' => 'محمد بن علي الحبسي',
                'contact_person_phone' => '+968 99234567',
                'contact_person_email' => 'mohammed@alnahda.om',
                'bank_name' => 'بنك ظفار',
                'bank_account' => '1234567890',
                'iban' => 'OM23DHOF1234567890123456',
                'swift_code' => 'DHOFOMR1',
                'notes' => 'متخصص في معدات البناء الثقيلة',
                'rating' => 4,
            ],
            [
                'supplier_number' => 'SUP-000003',
                'name' => 'خالد بن سعيد البلوشي',
                'email' => 'khalid.albalushi@email.om',
                'phone' => '+968 99345678',
                'address' => 'نزوى، حارة اليمن',
                'nationality' => 'عماني',
                'supplier_type' => 'INDIVIDUAL',
                'commercial_record' => null,
                'tax_number' => null,
                'status' => 'ACTIVE',
                'registration_date' => '2021-03-10',
                'contact_person' => 'خالد بن سعيد البلوشي',
                'contact_person_phone' => '+968 99345678',
                'contact_person_email' => 'khalid.albalushi@email.om',
                'bank_name' => 'البنك الأهلي',
                'bank_account' => '2345678901',
                'iban' => 'OM34NBOB2345678901234567',
                'swift_code' => 'NBOBOMR1',
                'notes' => 'تاجر معدات صغيرة، أسعار منافسة',
                'rating' => 3,
            ],
            [
                'supplier_number' => 'SUP-000004',
                'name' => 'مؤسسة الخليج للتجارة',
                'email' => 'info@gulf-trading.om',
                'phone' => '+968 24345678',
                'address' => 'صحار، المنطقة الصناعية',
                'nationality' => 'عماني',
                'supplier_type' => 'COMPANY',
                'commercial_record' => 'CR-2018-34567',
                'tax_number' => 'TAX-OM-345678',
                'status' => 'ACTIVE',
                'registration_date' => '2018-09-05',
                'contact_person' => 'سعيد بن محمد الشحي',
                'contact_person_phone' => '+968 99456789',
                'contact_person_email' => 'saeed@gulf-trading.om',
                'bank_name' => 'بنك مسقط',
                'bank_account' => '3456789012',
                'iban' => 'OM45BMAG3456789012345678',
                'swift_code' => 'BMAGOMR1',
                'notes' => 'مورد معدات متنوعة',
                'rating' => 4,
            ],
            [
                'supplier_number' => 'SUP-000005',
                'name' => 'شركة الأمل للاستيراد والتصدير',
                'email' => 'import@alamal.om',
                'phone' => '+968 24456789',
                'address' => 'مسقط، الخوير',
                'nationality' => 'عماني',
                'supplier_type' => 'COMPANY',
                'commercial_record' => 'CR-2017-45678',
                'tax_number' => 'TAX-OM-456789',
                'status' => 'ACTIVE',
                'registration_date' => '2017-11-12',
                'contact_person' => 'فاطمة بنت أحمد الكلبانية',
                'contact_person_phone' => '+968 99567890',
                'contact_person_email' => 'fatima@alamal.om',
                'bank_name' => 'بنك صحار الدولي',
                'bank_account' => '4567890123',
                'iban' => 'OM56SOHR4567890123456789',
                'swift_code' => 'SOHROMR1',
                'notes' => 'استيراد من الصين والهند',
                'rating' => 4,
            ],
            [
                'supplier_number' => 'SUP-000006',
                'name' => 'عبدالله بن راشد العبري',
                'email' => 'abdullah.alabri@email.om',
                'phone' => '+968 99678901',
                'address' => 'الرستاق، ولاية الرستاق',
                'nationality' => 'عماني',
                'supplier_type' => 'INDIVIDUAL',
                'commercial_record' => null,
                'tax_number' => null,
                'status' => 'INACTIVE',
                'registration_date' => '2022-02-14',
                'contact_person' => 'عبدالله بن راشد العبري',
                'contact_person_phone' => '+968 99678901',
                'contact_person_email' => 'abdullah.alabri@email.om',
                'bank_name' => 'البنك الأهلي',
                'bank_account' => '5678901234',
                'iban' => 'OM67NBOB5678901234567890',
                'swift_code' => 'NBOBOMR1',
                'notes' => 'مورد محلي صغير',
                'rating' => 2,
            ],
            [
                'supplier_number' => 'SUP-000007',
                'name' => 'مؤسسة الرواد للمعدات',
                'email' => 'contact@alrawad.om',
                'phone' => '+968 24567890',
                'address' => 'مسقط، القرم',
                'nationality' => 'عماني',
                'supplier_type' => 'COMPANY',
                'commercial_record' => 'CR-2021-56789',
                'tax_number' => 'TAX-OM-567890',
                'status' => 'ACTIVE',
                'registration_date' => '2021-07-08',
                'contact_person' => 'ياسر بن خميس الحارثي',
                'contact_person_phone' => '+968 99789012',
                'contact_person_email' => 'yasser@alrawad.om',
                'bank_name' => 'بنك ظفار',
                'bank_account' => '6789012345',
                'iban' => 'OM78DHOF6789012345678901',
                'swift_code' => 'DHOFOMR1',
                'notes' => 'معدات حديثة وصيانة ممتازة',
                'rating' => 5,
            ],
            [
                'supplier_number' => 'SUP-000008',
                'name' => 'شركة البناء الحديث',
                'email' => 'info@modernbuild.om',
                'phone' => '+968 24678901',
                'address' => 'صلالة، صلالة الجديدة',
                'nationality' => 'عماني',
                'supplier_type' => 'COMPANY',
                'commercial_record' => 'CR-2020-67890',
                'tax_number' => 'TAX-OM-678901',
                'status' => 'SUSPENDED',
                'registration_date' => '2020-04-22',
                'contact_person' => 'حمود بن سالم الريامي',
                'contact_person_phone' => '+968 99890123',
                'contact_person_email' => 'hamood@modernbuild.om',
                'bank_name' => 'بنك مسقط',
                'bank_account' => '7890123456',
                'iban' => 'OM89BMAG7890123456789012',
                'swift_code' => 'BMAGOMR1',
                'notes' => 'معلق بسبب تأخير في التوريد',
                'rating' => 2,
            ],
            [
                'supplier_number' => 'SUP-000009',
                'name' => 'مريم بنت علي الشكيلية',
                'email' => 'maryam.alshkaili@email.om',
                'phone' => '+968 99901234',
                'address' => 'البريمي، ولاية البريمي',
                'nationality' => 'عماني',
                'supplier_type' => 'INDIVIDUAL',
                'commercial_record' => null,
                'tax_number' => null,
                'status' => 'ACTIVE',
                'registration_date' => '2021-10-30',
                'contact_person' => 'مريم بنت علي الشكيلية',
                'contact_person_phone' => '+968 99901234',
                'contact_person_email' => 'maryam.alshkaili@email.om',
                'bank_name' => 'بنك صحار الدولي',
                'bank_account' => '8901234567',
                'iban' => 'OM90SOHR8901234567890123',
                'swift_code' => 'SOHROMR1',
                'notes' => 'تاجرة مواد بناء صغيرة',
                'rating' => 3,
            ],
            [
                'supplier_number' => 'SUP-000010',
                'name' => 'مؤسسة العز للتجارة',
                'email' => 'sales@alezz.om',
                'phone' => '+968 24789012',
                'address' => 'مسقط، الموالح',
                'nationality' => 'عماني',
                'supplier_type' => 'COMPANY',
                'commercial_record' => 'CR-2019-78901',
                'tax_number' => 'TAX-OM-789012',
                'status' => 'ACTIVE',
                'registration_date' => '2019-12-18',
                'contact_person' => 'سليمان بن ناصر الشبيبي',
                'contact_person_phone' => '+968 99012345',
                'contact_person_email' => 'sulaiman@alezz.om',
                'bank_name' => 'البنك الأهلي',
                'bank_account' => '9012345678',
                'iban' => 'OM01NBOB9012345678901234',
                'swift_code' => 'NBOBOMR1',
                'notes' => 'مورد شامل لجميع الاحتياجات',
                'rating' => 4,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }
    }
}
